apiVersion: openapi/v2
kind: Deployment
metadata:
  labels:
    app: kubesphere
    component: ks-docs-sample-dev
    tier: backend
  name: ks-docs-sample-dev
  namespace: kubesphere-docs-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: kubesphere
      component: ks-docs-sample-dev
      tier: backend
  template:
    metadata:
      labels:
        app: kubesphere
        component: ks-docs-sample-dev
        tier: backend
    spec:
      containers:
      - env:
        - name: CACHE_IGNORE
          value: js|html
        - name: CACHE_PUBLIC_EXPIRATION
          value: 3d
        image: $HARBOR_NAMESPACE/$APP_NAME:SNAPSHOT-CRON-BUILD-$BUILD_NUMBER
        imagePullPolicy: Always
        name: ks-docs
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
