apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesphere
    component: ks-docs-sample-dev
  name: ks-docs-sample-dev
  namespace: kubesphere-docs-dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30860
  selector:
    app: kubesphere
    component: ks-docs-sample-dev
    tier: backend
  sessionAffinity: None
  type: NodePort
